<?php


/**
 * Renders a system default template, which is essentially a PHP template.
 *
 * @param string $template_file
 *   Template file path.
 * @param array $variables
 *    A keyed array of variables that will appear in the output.
 *
 * @return string
 *   The output generated by the template.
 */
function gbooks_render_template($template_file, $variables) {
  // Extract the variables to a local namespace
  extract($variables, EXTR_SKIP);

  // Start output buffering
  ob_start();

  // Include the template file
  include SITE_ROOT . '/' . $template_file;

  // End buffering and return its contents
  return ob_get_clean();
}
